pipeline {
    agent any
    stages {
        stage('checkout') {
            steps {
                checkout scm
            }
        }
        stage('build') {
            agent {
                docker {
                    image 'node:14'
                }
            }
            steps {
                sh 'npm install'
                sh 'npm run build'
            }
        }
        stage('package') {
            steps {
                sh 'jar cMf lambda.zip -C build/ .'
                archiveArtifacts artifacts: 'lambda.zip', fingerprint: true
            }
        }
    }
}
