pipeline {
    agent any
    stages {
        stage('checkout') {
            steps {
                checkout scm
            }
        }
        stage('build') {
            agent {
                docker {
                    image 'node:14'
                }
            }
            steps {
                dir('example1/vpc1-lambda') {
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }
        stage('package') {
            steps {
                dir('example1/vpc1-lambda') {
                    sh 'jar cMf lambda.zip index.js'
                    archiveArtifacts artifacts: 'lambda.zip', fingerprint: true
                }
            }
        }
    }
}
